# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"

title                    : "Forough Fazeliasl"
title_separator          : "-"
name                     : &name "Forough Fazeliasl"
description              : &description "Postdoctoral Fellow in deep learning, Bayesian nonparametrics, machine learning, privacy, and fairness."

url                      : "https://foroughfazeliasl.github.io"
baseurl                  : ""
repository               : "ForoughFazeliasl/ForoughFazeliasl.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Forough Fazeliasl"
  pronouns         : "She/Her"
  bio              : "Postdoctoral Fellow and Assistant Lecturer at the University of Alberta working on Bayesian nonparametrics, deep learning, generative models, fairness, and data privacy."
  location         : "Alberta, Canada"
  employer         : "University of Alberta"
  uri              : "https://apps.ualberta.ca/directory/person/fazelias"
  email            : "fazelias@ualberta.ca"

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=x8w4k_EAAAAJ&hl=en&oi=ao"
  inspire-hep      :
  impactstory      :
  orcid            : "https://orcid.org/0000-0001-5885-0946"
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "ForoughFazeliasl"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

comments:
  provider               :
disqus:
  shortname              :
discourse:
  server                 :
facebook:
  appid                  :
  num_posts              :
  colorscheme            :

staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"

atom_feed:
  hide                   : false
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :
og_description           :

social:
  type                   :
  name                   :
  links:
    -

# Analytics
analytics:
  provider               : "false"
google:
  tracking_id            :

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:
  - jekyll-feed
  - jekyll-sitemap
